### ISSUE TITLE
Outdated, we should use the official plugin 'point-of-view' instead for now

### ISSUE THREAD

**Issue by ash-r1** [SerayaEryn/fastify-pug#65]
This plugin is using the deprecated API, thus fastify says `You are decorating Request/Reply with a reference type` on running.
Also, it has no TypeScript type definition.

As official https://github.com/fastify/point-of-view supports plugin supports pug.

No offense, I would like to suggest other developers.
I respect the owner of this plugin, who published a well-developed useful plugin.

Thanks.

**Comment by SerayaEryn** [comment]
I agree. I will archive the repository.
